In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import accuracy_score
from tensorflow.keras.preprocessing.image import load_img,img_to_array
from keras.preprocessing.image import img_to_array
from tensorflow.keras.utils import to_categorical

In [2]:
base_dir="dataset/"

In [3]:
class_labels=os.listdir(base_dir)
print(class_labels)

['EA', 'EH', 'EP', 'NE']


In [4]:
data=[]
count=0

for label in class_labels:
    i=0
    path = os.path.join(base_dir, label)
    print(path)
    for img in os.listdir(path):
        try:
            image=load_img(os.path.join(path, img), grayscale=True, color_mode='grayscale', target_size=(128,128))
            image=img_to_array(image)
            image=image/255.0
            data.append([image,count])
        except Exception as e:
                pass
    count=count+1

dataset/EA
dataset/EH
dataset/EP
dataset/NE


In [5]:
data=[]
count=0

for label in class_labels:
    i=0
    path = os.path.join(base_dir, label)
    print(path)
    for img in os.listdir(path):
        try:
            image = load_img(os.path.join(path, img), color_mode='grayscale', target_size=(128,128))
            image=img_to_array(image)
            image=image/255.0
            data.append([image,count])
        except Exception as e:
                pass
    count=count+1

dataset/EA
dataset/EH
dataset/EP
dataset/NE


In [6]:
print(len(data))

3198


In [7]:
X,y =zip(*data)

In [8]:
X

(array([[[0.31764707],
         [0.34509805],
         [0.39607844],
         ...,
         [0.20784314],
         [0.20784314],
         [0.43137255]],
 
        [[0.35686275],
         [0.41568628],
         [0.4392157 ],
         ...,
         [0.3647059 ],
         [0.2627451 ],
         [0.52156866]],
 
        [[0.6392157 ],
         [0.3882353 ],
         [0.2784314 ],
         ...,
         [0.28235295],
         [0.15686275],
         [0.6745098 ]],
 
        ...,
 
        [[0.18431373],
         [0.27450982],
         [0.3137255 ],
         ...,
         [0.8117647 ],
         [0.8156863 ],
         [0.8039216 ]],
 
        [[0.36078432],
         [0.25882354],
         [0.21960784],
         ...,
         [0.8       ],
         [0.8117647 ],
         [0.8039216 ]],
 
        [[0.38039216],
         [0.28627452],
         [0.2627451 ],
         ...,
         [0.61960787],
         [0.7176471 ],
         [0.7882353 ]]], shape=(128, 128, 1), dtype=float32),
 array([[[0.4745098

In [9]:
print(y)

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [10]:
data=[]
count=0

for label in class_labels:
    i=0
    path = os.path.join(base_dir, label)
    print(path)
    for img in os.listdir(path):
        try:
            image=load_img(os.path.join(path, img), grayscale=True, color_mode='grayscale', target_size=(128,128))
            image=img_to_array(image)
            image=image/255.0
            data.append([image,count])
        except Exception as e:
                pass
    count=count+1

dataset/EA
dataset/EH
dataset/EP
dataset/NE


In [11]:
print(len(data))

0


In [12]:
data=[]
count=0

for label in class_labels:
    i=0
    path = os.path.join(base_dir, label)
    print(path)
    for img in os.listdir(path):
        try:
            image = load_img(os.path.join(path, img), color_mode='grayscale', target_size=(128,128))
            image=img_to_array(image)
            image=image/255.0
            data.append([image,count])
        except Exception as e:
                pass
    count=count+1

dataset/EA
dataset/EH
dataset/EP
dataset/NE


In [13]:
print(len(data))

3198


In [14]:
X,y =zip(*data)

In [15]:
X

(array([[[0.31764707],
         [0.34509805],
         [0.39607844],
         ...,
         [0.20784314],
         [0.20784314],
         [0.43137255]],
 
        [[0.35686275],
         [0.41568628],
         [0.4392157 ],
         ...,
         [0.3647059 ],
         [0.2627451 ],
         [0.52156866]],
 
        [[0.6392157 ],
         [0.3882353 ],
         [0.2784314 ],
         ...,
         [0.28235295],
         [0.15686275],
         [0.6745098 ]],
 
        ...,
 
        [[0.18431373],
         [0.27450982],
         [0.3137255 ],
         ...,
         [0.8117647 ],
         [0.8156863 ],
         [0.8039216 ]],
 
        [[0.36078432],
         [0.25882354],
         [0.21960784],
         ...,
         [0.8       ],
         [0.8117647 ],
         [0.8039216 ]],
 
        [[0.38039216],
         [0.28627452],
         [0.2627451 ],
         ...,
         [0.61960787],
         [0.7176471 ],
         [0.7882353 ]]], shape=(128, 128, 1), dtype=float32),
 array([[[0.4745098

In [16]:
X=np.array(X)
y=np.array(y)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


In [18]:
import numpy as np
from skimage.feature import hog
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Function to extract HOG features
def extract_hog_features(images):
    features = []
    for img in images:
        img_2d = img.squeeze()
        hog_feature = hog(img_2d, pixels_per_cell=(8,8), cells_per_block=(2,2), visualize=False)
        features.append(hog_feature)
    return np.array(features)

# Extract HOG features for train and test sets
X_train_hog = extract_hog_features(X_train)
X_test_hog = extract_hog_features(X_test)

# Train the SVM model
svm_model = SVC(kernel='rbf', probability=True)
svm_model.fit(X_train_hog, y_train)

# Predict and evaluate accuracy
y_pred = svm_model.predict(X_test_hog)
accuracy = accuracy_score(y_test, y_pred)
print(f"SVM Test Accuracy: {accuracy*100:.2f}%")


SVM Test Accuracy: 42.81%
